kind: Service
apiVersion: v1
metadata:
  name: go-test{{ .Values.suffix }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    component: go-test{{ .Values.suffix }}
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.containerPort }}
